#!/usr/bin/env bash
print_help() {
    cat <<EOF
dotfiles

USAGE:
    dotfiles <SUBCOMMAND>

OPTIONS:
    -h, --help    Print help information

SUBCOMMANDS:
    help      Print this message
    update    Restow
    clean     Remove all stow symlinks
EOF
}

check_deps() {
    if ! command -v stow >/dev/null 2>&1; then
        >&2 echo "Command 'stow' not available"
        exit 1
    fi
    if ! command -v curl >/dev/null 2>&1; then
        >&2 echo "Command 'curl' not available"
        exit 1
    fi
}

case $1 in
    update)
        check_deps
        stow --no-folding -R . -t ~/

        git_prompt_location="$HOME/.config/bash/git-prompt.sh"
        [ -f "$git_prompt_location" ] || {
            curl -sL "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh" -o "$git_prompt_location" || {
                echo >&2 "Failed to fetch git-prompt.sh from github"
                exit 1
            }
            sed -i '1s/^/#!\/bin\/bash\n/' "$git_prompt_location"
        }
        ;;
    clean)
        check_deps
        stow -D . -t ~/
        ;;
    -h | --help | help)
        print_help
        ;;
    *)
        print_help
        exit 2
        ;;
esac
