#!/usr/bin/env bash
print_help() {
    cat <<EOF
dotfiles

USAGE:
    dotfiles <SUBCOMMAND>

OPTIONS:
    -h, --help    Print help information

SUBCOMMANDS:
    help      Print this message
    update    Restow
    clean     Remove all stow symlinks
EOF
}

check_deps() {
    if ! command -v stow >/dev/null 2>&1; then
        >&2 echo "Command 'stow' not available"
        exit 1
    fi
    if ! command -v curl >/dev/null 2>&1; then
        >&2 echo "Command 'curl' not available"
        exit 1
    fi
}

download_file() {
    location="$1"
    url="$2"
    [ -f "$location" ] || {
        curl -sL "$url" -o "$location" || {
            echo >&2 "Failed to fetch $url"
            exit 1
        }
    }
}

case $1 in
    update)
        check_deps
        stow --no-folding -R . -t ~/

        base="$HOME/.config/bash"
        git_prompt_location="$base/git-prompt.sh"
        download_file "$git_prompt_location" "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh"
        # sed -i '1s/^/#!\/bin\/bash\n/' "$git_prompt_location"
        download_file "$base/fzf-completion.bash" "https://raw.githubusercontent.com/junegunn/fzf/master/shell/completion.bash"
        download_file "$base/fzf-key-bindings.bash" "https://raw.githubusercontent.com/junegunn/fzf/master/shell/key-bindings.bash"
        download_file "$base/bash-completion.bash" "https://raw.githubusercontent.com/scop/bash-completion/master/bash_completion"
        ;;
    clean)
        check_deps
        stow -D . -t ~/
        ;;
    -h | --help | help)
        print_help
        ;;
    *)
        print_help
        exit 2
        ;;
esac
