require('plugins')
require('options')
require('keymap')
require('lsp')
require('nvim-cmp')
require('relativenumber')
require('noswap')
require('treesitter')
require('statusline')
require('netrw')
require('colors')

vim.cmd('source ' .. vim.fn.stdpath('config') .. "/" .. "initialize.vim")
-- vim.cmd('source ~/.config/nvim/initialize.vim')
